# Generated by Django 5.0.2 on 2024-11-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogsUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='modulos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LogsError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_error', models.CharField(max_length=255)),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_error', models.TimeField()),
                ('fecha_error', models.DateField()),
                ('tipo_error', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_error', to='modulos.usuario')),
            ],
        ),
    ]
